Add redis operator and redis resources
cloudnativedaysjp/dreamkast-infra pull request #1019
Opened 2021-10-13 10:16 UTC by inductor

https://ot-container-kit.github.io/redis-operator/ の導入

ClusterとStandalone両方あって、Staging/Productionではクラスターを、DevではStandaloneで動かす
本PRではOperatorの全環境へのインストールと、一旦Dev用のTemplateだけにRedis環境の置き換えを反映しました

2021-10-14 00:58 UTC, jacopen requested changes

2021-10-14 00:58 UTC, jacopen commented on manifests/app/dreamkast/overlays/template/redis.yaml
> +  namespace: ot-operators
全体的にネームスペース名がバラバラな気がする？

2021-10-14 00:58 UTC, jacopen commented on manifests/app/dreamkast/overlays/template/deployment-mail-worker.yaml
> +          value: "redis://redis-headless:6379"
redis-headlessというsvcはどこで作られるんだろ

2021-10-14 00:58 UTC, jacopen commented on manifests/app/dreamkast/overlays/template/redis.yaml
> +  namespace: ot-operators
kind: Redis　のものがredisのインスタンスになる認識なんだけど、各Review appsと異なるNSに入ると名前解決的にどうなるのかな

2021-10-14 03:28 UTC, inductor commented on manifests/app/dreamkast/overlays/template/redis.yaml
> +  namespace: ot-operators
あ、これは間違ってるので直します。

2021-10-21 11:54 UTC, oke-py reviewed
helmで入れるより自前でマニフェスト管理した方がいいんですか？

2021-10-21 11:54 UTC, oke-py commented on manifests/infra/redis-operator/base/role_binding.yaml
> +  name: cluster-admin
公式も`cluster-admin`になっていますが、これじゃないんですかねー
```suggestion
  name: manager-role-redis-operator
```

2021-10-30 11:41 UTC, closed without merging