Remove prometheus app selector
cloudnativedaysjp/dreamkast-infra pull request #1231
Opened 2021-11-22 13:53 UTC by mayocream

Fix #1230

2021-11-22 13:55 UTC, inductor commented on manifests/infra/prometheus/base/prometheus.yaml
> -    app: prometheus
@mayocream Seems like it can be applied to production since it's in `base`, could you make sure this change will be fine on production as well?
CC: @oke-py

2021-11-22 14:05 UTC, mayocream commented on manifests/infra/prometheus/base/prometheus.yaml
> -    app: prometheus
Oh, This should not be applied to the prod env. It's a patch for the dev env.

2021-11-22 14:12 UTC, inductor commented on manifests/infra/prometheus/base/prometheus.yaml
> -    app: prometheus
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/0f561ea3b173c10fc93a094d88a48ace089db248/manifests/infra/prometheus/overlays/production/kustomization.yaml#L5

This will be loaded. My concern here is if 0.48.1 has forward compatibility with this change or not.

2021-11-22 14:52 UTC, mayocream commented
@inductor The first commit is wrong. I force-pushed a new commit, now the patch only works for dev.

2021-11-22 16:33 UTC, inductor requested changes

2021-11-22 16:33 UTC, inductor commented on manifests/infra/prometheus/overlays/development/service-selector.yaml
> +
<img width="292" alt="image" src="https://user-images.githubusercontent.com/20236173/142899212-0cb18501-6607-49d7-b454-990a21c50999.png">

EOL is not proper here 🤔

2021-11-22 18:02 UTC, mayocream commented on manifests/infra/prometheus/overlays/development/service-selector.yaml
> +
🤔need to force push again. 寝不足頭がおかしくなる

2021-11-22 18:12 UTC, inductor commented on manifests/infra/prometheus/overlays/development/service-selector.yaml
> +
Please get some 睡眠

2021-11-23 10:19 UTC, oke-py approved these changes
こういう書き方ができるんですね。
手元で`kustomize build overlays/development`の出力を確認しました。

2021-11-23 10:25 UTC, inductor approved these changes

2021-11-23 10:25 UTC, merged