dev: refacor argo project
cloudnativedaysjp/dreamkast-infra pull request #1256
Opened 2021-11-28 08:41 UTC by inductor

ArgoCDのプロジェクトをインフラ、アプリ、監視の観点で分けるようにした

ReviewApps Operatorについてはこれでよいか要検討である

2021-11-28 08:42 UTC, inductor commented on manifests/argocd-apps/dev/reviewapp-operator.yaml
> +  project: app
自前でコード書いてるしappに含めちゃったけどSREって意味だとインフラとも言えるのでこれはどうしようかしらね @ShotaKitazawa

2021-11-28 08:46 UTC, oke-py commented
よさそうですね。projectを事前に作成しておく必要があるのかだけ気になるところです。

2021-11-28 08:52 UTC, inductor commented
試しになにかひとつapplyしてみよう

2021-11-28 08:55 UTC, inductor commented
エラーでおこられた！
https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#projects
これが必要だ

2021-11-28 09:08 UTC, inductor commented on manifests/argocd/base/projects.yaml
> +  - '*'
AppProjectを足した！

2021-11-28 10:36 UTC, ShotaKitazawa commented on manifests/argocd-apps/dev/reviewapp-operator.yaml
> +  project: app
ArgoCD と reviewapp-operator は `infra` ではなく `cd` プロジェクトにするのはどうでしょう？

2021-11-29 07:12 UTC, oke-py requested changes

2021-11-29 07:12 UTC, oke-py commented on manifests/argocd/base/projects.yaml
> +  - '*'
```suggestion
```
同じフィールドが2回出てきています。他のAppProjectも同様です。

2021-11-29 07:16 UTC, inductor commented on manifests/argocd/base/projects.yaml
> +  - '*'
Oops!

2021-11-29 07:18 UTC, oke-py approved these changes

2021-11-29 07:23 UTC, merged