WIP add telegraf sql exporter
cloudnativedaysjp/dreamkast-infra pull request #1280
Opened 2021-12-07 07:00 UTC by mhoshi-vm

# Description

TelegrafによるRDS側のデータベースのスクレイプとメトリクス化

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

WIP

2021-12-10 16:04 UTC, mhoshi-vm commented
この方法で以下のメトリクスが取れることを確認しています。値に入るのはDatabaseのID
```
dreamkast_talks_id{execution_phases="[9]",expected_participants="[1, 2, 4]",talk_category="",talk_difficulity="中級者",title="ArgoCDとTerraformを用いたInfrastructure as Codeの実践"} 1160
dreamkast_talks_id{execution_phases="[9]",expected_participants="[2, 3, 4]",talk_category="",talk_difficulity="中級者",title="コロプラにおけるアプリケーションとインフラ基盤の継続的デリバリー"} 1159
dreamkast_talks_id{execution_phases="[9]",expected_participants="[4, 6]",talk_category="",talk_difficulity="中級者",title="Continuous Documentation - CI/CDパイプラインを活用した文書化技術 -"} 1170
```
さらにgithubのIssueなどのおまけの情報も追加しました。ちなみに、GithubのAPIの制限のため、1hごとにクエリをかけています。

2021-12-10 16:08 UTC, mhoshi-vm commented
@jacopen 
ちなみに、execution_phasesとexpected_participantsはJSON形式になっており、RDSからだけでは文字列に変換するのは不可能と判断しましたが、正しいですかね？

2021-12-10 16:11 UTC, inductor reviewed
全体的にnamespaceはどこに統一するか検討できてますか？

2021-12-10 16:46 UTC, jacopen commented
> @jacopen ちなみに、execution_phasesとexpected_participantsはJSON形式になっており、RDSからだけでは文字列に変換するのは不可能と判断しましたが、正しいですかね？

そうですね、恐らくシンプルなクエリで解決するのは難しいと思います。
proposal_item_configsテーブルの中のものと、ActiveRecordを使って紐付けているので今回の場合は文字列を持ってくるのは難しいかなと。

https://github.com/cloudnativedaysjp/dreamkast/blob/main/app/models/talk.rb#L237-L247

2021-12-15 06:00 UTC, mhoshi-vm commented
結局 #1252 を問題があるので、いまMergeしても一日分のデータしか入らない問題に

2021-12-15 11:29 UTC, inductor requested changes

2021-12-15 11:29 UTC, inductor commented on manifests/infra/telegraf/overlay/production/deployment.yaml
> +            value: "dreamkast-prd-rds.c6eparu1hmbv.ap-northeast-1.rds.amazonaws.com"
Productionにはまだ入れないほうがいいと思うので、一旦Dev(というかStaging)のほうだけでやりたいんですがどうでしょうか

2021-12-15 11:44 UTC, inductor requested changes

2021-12-15 11:44 UTC, inductor commented on manifests/infra/telegraf/overlay/production/kustomization.yaml
> +- deployment.yaml
同じくここも

2021-12-16 11:18 UTC, riita10069 commented on manifests/infra/telegraf/overlay/development/configmap.yaml
> +        query="SELECT t.id,t.title,td.name AS talk_difficulity,tc.name AS talk_category,t.expected_participants,t.execution_phases,p.label AS proposed_labels,p.params AS proposed_params FROM talks t
このselectで得られたものをPrometheusに流す感じですよね。
そしたら、実行するたびに同じ行がPrometheusに追加されてしまう気がするんですけど、そういうことではないんですかね。

2021-12-16 13:35 UTC, mhoshi-vm commented
新しいコミットで以下を対応
• CONF_IDでWHERE文を制御
• proposal_itemは別テーブルとして検索を分割

結果として以下のようにとれるようになりました

```
dreamkast_talks_id{talk_category="Keynote",talk_difficulity="初級者",title="How We Harden Platform Security at Mercari"} 1208
dreamkast_talks_id{talk_category="Keynote",talk_difficulity="初級者",title="Kubernetes On-premises is Hardway?"} 1281
dreamkast_talks_id{talk_category="Keynote",talk_difficulity="初級者",title="Mableの高速開発を支えるプラットフォーム"} 1203
dreamkast_talks_id{talk_category="Keynote",talk_difficulity="初級者",title="Open Standards: Anchoring Extensibility for Cloud-Native Tooling"} 1305
```
```
dreamkast_proposal_items_talk_id{label="language",params="\"26\"",talk_id="1259"} 1259
dreamkast_proposal_items_talk_id{label="language",params="\"26\"",talk_id="1260"} 1260
dreamkast_proposal_items_talk_id{label="language",params="\"26\"",talk_id="1262"} 1262
dreamkast_proposal_items_talk_id{label="language",params="\"26\"",talk_id="1263"} 1263
dreamkast_proposal_items_talk_id{label="language",params="\"26\"",talk_id="1264"} 1264
dreamkast_proposal_items_talk_id{label="language",params="\"26\"",talk_id="1265"} 1265```

2021-12-16 13:48 UTC, inductor requested changes

2021-12-16 13:48 UTC, inductor commented on manifests/infra/telegraf/overlay/production/configmap.yaml
> +    #  ]
レビューのとき混乱するので一旦production以下は何も追加しないようにしてほしいかもです

2021-12-16 13:51 UTC, mhoshi-vm commented on manifests/infra/telegraf/overlay/production/configmap.yaml
> +    #  ]
ありがとうございます。Production関連いったん全部抜きました。

2021-12-16 13:56 UTC, inductor commented on manifests/infra/telegraf/overlay/development/configmap.yaml
> +
ここらへんの設定って環境ごとに変える必要ないならbaseで良いと思ったのですが、どうでしょう。

2021-12-16 13:57 UTC, inductor commented on manifests/infra/telegraf/base/deployment.yaml
> +            value: "2"
このCONF_ID = 2ってなんのやつでしたっけ

2021-12-16 14:06 UTC, mhoshi-vm commented on manifests/infra/telegraf/base/deployment.yaml
> +            value: "2"
これBaseにいれているだけ（手元の検証がまだCONF_ID ５がないので）で、overlay側で5 になります。ややこしければぬきます。
https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1280/files#diff-0f634d4f091e3d0e8f2bd1d86473252b8184e7d7e6494b2e1c1e330f7c58465e

2021-12-16 14:09 UTC, mhoshi-vm commented on manifests/infra/telegraf/overlay/development/configmap.yaml
> +
そうですね。これは直してCommitしなおしました。

2021-12-16 14:10 UTC, mhoshi-vm commented on manifests/infra/telegraf/overlay/development/configmap.yaml
> +        query="SELECT t.id,t.title,td.name AS talk_difficulity,tc.name AS talk_category,t.expected_participants,t.execution_phases,p.label AS proposed_labels,p.params AS proposed_params FROM talks t
prometheus側で時系列情報が追加されるので、そのタイミングのこのSQL結果が遷移していくイメージです。

2021-12-16 15:00 UTC, riita10069 commented on manifests/infra/telegraf/overlay/development/configmap.yaml
> +        query="SELECT t.id,t.title,td.name AS talk_difficulity,tc.name AS talk_category,t.expected_participants,t.execution_phases,p.label AS proposed_labels,p.params AS proposed_params FROM talks t
なるほど。少し勘違いしてました。
PrometheusのQueryの表現力があまりわからないんですけど、こういうのって
知りたいデータに対して、Exportするようなイメージになるわけではないんですかね？

例えば、「合計CFP数」が知りたいなら、

```
select count(distinct id) from talks where conf_id = 5
```

みたいなイメージを持っていたのですが、
とりあえず丸っとPrometheusに入れて、PromQL側のクエリでグラフを作るような感じになるのでしょうか？

2021-12-16 23:21 UTC, iaoiui commented on manifests/infra/telegraf/overlay/development/configmap.yaml
> +        query="SELECT t.id,t.title,td.name AS talk_difficulity,tc.name AS talk_category,t.expected_participants,t.execution_phases,p.label AS proposed_labels,p.params AS proposed_params FROM talks t
このPR取り込み後で別途相談させてもらいたいのですが、もしかしたら「CFPのカウントメトリクス」と、「その他DreamkastのDBから持ってこれる静的メトリクス」を分けると、シンプルになるかもと思いました。
時系列で変化していかないデータ部分(想定受講者, 実行フェーズ, 講演言語 - Language, etc)は、いっそのことPrometheusに投げないことでメトリクスストレージの節約をしつつ、GrafanaのMySQL Data sourceから持ってきて別途円グラフなどで割合を見せるなども良さそうと思いました。
https://grafana.com/docs/grafana/latest/datasources/mysql/


[[inputs.sql.query]]ブロックを増やすこと自体は問題なさそうなので、 @riita10069 さんが提示してる下記SQL
も実装に取り込んでおくことで、Pros/Consを後々整理しやすいかと思います。
```
select count(distinct id) from talks where conf_id = 5
```

2021-12-16 23:22 UTC, iaoiui approved these changes

2021-12-17 01:16 UTC, merged