オブザーバビリティ用のDBをわけたい
cloudnativedaysjp/dreamkast-infra pull request #1299
Opened 2021-12-16 15:18 UTC by riita10069

# Description

Fixes #1298 

## Type of change

- [ ] Document update or simple typo fix
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] I have checked backward/forward compatibility that may cause regarding this change.

2021-12-16 15:25 UTC, riita10069 commented
参考：https://gist.github.com/inductor/2934e5123f90463a825f8903b2b79dd5

2021-12-20 12:31 UTC, oke-py commented on manifests/infra/mysql-o11y/cronjob.yaml
> +  user: cm9vdAo=
user/passwordをGitHubに載せるのはまずいので、ExternalSecretを使うようにしてもらえますか？
このあたりを参照してやってみてください。わからないことがあればSlackでじゃんじゃん聞いてください。
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/infra/telegraf/overlays/development/secrets.yaml

RDSと別のuser/passwordにすべきですかね・・・。まだAWSの権限もらっていないようであればこちらでやりますので言ってください。

2021-12-24 12:07 UTC, oke-py commented
@inductor こちらのサポートお願いします:bow:

2021-12-28 08:29 UTC, riita10069 commented
External Secretについては[ここ](https://cloudnativedays.slack.com/archives/C02MAP9EHAA/p1640679091425100?thread_ts=1640676542.412800&cid=C02MAP9EHAA)

2021-12-28 10:36 UTC, oke-py commented
argocdのApplicationを↓に作成してみてください（その間にレビューしておきます）。
devだけでOKです。マージ後に動作確認できてからprd用のPR出してもらいます。
https://github.com/cloudnativedaysjp/dreamkast-infra/tree/main/manifests/argocd-apps/dev

2021-12-29 09:13 UTC, ryojsb requested changes

2021-12-29 09:13 UTC, ryojsb commented on manifests/infra/mysql-o11y/overlays/production/kustomization.yaml
> +apiVersion: kustomize.config.k8s.io/v1beta1
いきなりProductionにも入れてしまって大丈夫でしょうか。
(devでの検証が済んでたらすみません。)

2021-12-31 17:14 UTC, riita10069 commented on manifests/infra/mysql-o11y/overlays/production/kustomization.yaml
> +apiVersion: kustomize.config.k8s.io/v1beta1
一旦、devだけで出した方がいい感じですかね？
argocd-appsがなければ、本番には上がらないはずなので作ってしまいました。

2022-01-01 00:20 UTC, oke-py commented on manifests/infra/mysql-o11y/overlays/production/kustomization.yaml
> +apiVersion: kustomize.config.k8s.io/v1beta1
> argocd-appsがなければ、本番には上がらない

これなので流していましたが、devだけからはじめる習慣をつけておくとよいですね。

2022-01-13 09:28 UTC, riita10069 commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +            args: ["mysqldump --single-transaction --quick --set-charset -u $RDS_USER -p $RDS_PASSWORD -h $RDS_HOST dreamkast conference_days conferences proposal_item_configs proposal_items proposal
コマンドの動作確認しました。
ローカルのMySQLからローカルのMySQLの別のテーブルに動かすことには成功しました！

2022-01-13 10:01 UTC, inductor commented on manifests/argocd-apps/dev/mysql-o11y.yaml
> +  project: mysql-o11y
このプロジェクトって存在しますっけ？

2022-01-13 12:22 UTC, riita10069 commented on manifests/argocd-apps/dev/mysql-o11y.yaml
> +  project: mysql-o11y
あ、ArgoCDのProject作ってないです:pray:
ProjectとRoleの定義ってどこにありますかね？

2022-01-15 03:46 UTC, inductor requested changes

2022-01-15 03:46 UTC, inductor commented on manifests/argocd-apps/dev/mysql-o11y.yaml
> +  project: mysql-o11y
```suggestion
  project: monitoring
```

2022-01-15 03:47 UTC, inductor commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +  namespace: mysql-o11y
ここもmonitoring namespaceでまとめてよさそうだけど分けてる理由あれば知りたいです

2022-01-15 03:47 UTC, inductor commented on manifests/infra/mysql-o11y/base/deployment.yaml
> +  namespace: mysql-o11y
ditto

2022-01-15 09:23 UTC, riita10069 commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +  namespace: mysql-o11y
monitoringはdreamkastチームのnamespaceなのかなと思い、
Observabilityチームのコンポートを一緒にしない方がいいのかなと思ったので、jobもMySQLも分けました。

2022-01-15 13:13 UTC, inductor commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +  namespace: mysql-o11y
特に分けてないですね

2022-01-15 13:19 UTC, riita10069 commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +  namespace: mysql-o11y
monitoring namespace使いますね

2022-01-23 10:21 UTC, oke-py commented
namespaceについては、年末のもくもく会で「今後もObservabilityチーム用の出てくるかもしれないし分ける？」とjacopenさん、riitaさんと話していました。
が、今のところ何かあるわけではないのでmonitoringにしましょうか。増えてきたらそのときに考える感じで。

namespaceを修正してもらったらマージしていいかなと思います。

2022-01-23 10:33 UTC, inductor commented
いや、分けるなら分けていいと思うんですが、だとしたらNamespaceを作る設定が入ってないのでそれも含めての確認でしたね（「分けてる理由あれば知りたい」のところで知りたかった背景）

2022-01-24 14:51 UTC, mhoshi-vm commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +  schedule: "*/1 * * * *"
これってcronの表現冗長じゃないですかね？毎分であれば"* * * * *"で/1する意味はないかと

2022-01-24 14:57 UTC, mhoshi-vm requested changes
要望の追加です

2022-01-24 15:01 UTC, riita10069 commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +  schedule: "*/1 * * * *"
ちなみに間隔どのくらいがいいと思いますか？
一時間おきくらいですかね？

2022-01-24 15:04 UTC, jacopen commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +            args: ["mysqldump --single-transaction --quick --set-charset -u $RDS_USER -p $RDS_PASSWORD -h $RDS_HOST dreamkast conference_days conferences proposal_item_configs proposal_items proposal
chat_messagesはユーザー投稿のメッセージそのものが入るので、含めずにダミーデータでお願いしたいです

2022-01-25 00:40 UTC, mhoshi-vm commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +  schedule: "*/1 * * * *"
結局このDBで当実のアクセス数などをとるので、システム負荷が許すのであれば可能な限り細かいほうがいいと思っています。

2022-01-25 01:58 UTC, oke-py commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +            args: ["mysqldump --single-transaction --quick --set-charset -u $RDS_USER -p $RDS_PASSWORD -h $RDS_HOST dreamkast conference_days conferences proposal_item_configs proposal_items proposal
https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1299#discussion_r790832166 `chat_messages`は別途検討しましょうか。
```suggestion
            args: ["mysqldump --single-transaction --quick --set-charset -u $RDS_USER -p $RDS_PASSWORD -h $RDS_HOST dreamkast conference_days conferences proposal_item_configs proposal_items proposals talk_categories talk_difficulties talk_times talks talks_speakers tracks stats_of_registrants viewer_counts > $HOME/rds.dump; mysql -u $MYSQL_USER -p $MYSQL_PASSWORD  -h $MYSQL_HOST dreamkast < $HOME/rds.dump"]
```

2022-01-25 13:41 UTC, mhoshi-vm commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +            args: ["mysqldump --single-transaction --quick --set-charset -u $RDS_USER -p $RDS_PASSWORD -h $RDS_HOST dreamkast conference_days conferences proposal_item_configs proposal_items proposal
失礼しました。これはフィルターできないのですね。では、一旦以下のみでお願いします。Chat Messagesは一旦この方法は諦めます。

- stats_of_registrants
- viewer_counts

2022-01-25 13:44 UTC, mhoshi-vm commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +            args: ["mysqldump --single-transaction --quick --set-charset -u $RDS_USER -p $RDS_PASSWORD -h $RDS_HOST dreamkast conference_days conferences proposal_item_configs proposal_items proposal
別コメントでもかきましたが、chat_messages は諦めます。お騒がせしました。

2022-01-25 16:06 UTC, riita10069 commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +  schedule: "*/1 * * * *"
なるほど。当日のアクセス数も取るのですね。
この処理によってリアルタイム性が損なわれる可能性があるということですかね？
mysqldumpの負荷がどの程度が分からないので、ひとまず毎秒にしてみます。

2022-01-25 16:21 UTC, oke-py commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +  schedule: "*/1 * * * *"
毎秒って簡単にできるんですか？
いったん現状でマージしてしまって動作確認に進みたい思いがあります。

2022-01-25 17:38 UTC, oke-py approved these changes
長期戦、ありがとうございました！
次回からはシュッといけるようにレビューする立場としても行動していきたいです。

2022-01-25 17:39 UTC, merged

2022-01-25 18:09 UTC, inductor commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +  schedule: "*/1 * * * *"
> 強くリアルタイム性を求められるデータは、API側でExporterを作成したほうがいいかなと個人的には思っています。

+1

2022-01-25 23:30 UTC, mhoshi-vm commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +  schedule: "*/1 * * * *"
この cron の書き方だと "毎分 " ですね。

2022-01-25 23:40 UTC, mhoshi-vm commented on manifests/infra/mysql-o11y/base/cronjob.yaml
> +  schedule: "*/1 * * * *"
API側でExporter書くとなるとちょっと時間ほしいので、とりあえず、これで動作確認させてください。