Enable Twitter exporter on production
cloudnativedaysjp/dreamkast-infra pull request #1403
Opened 2022-02-03 15:35 UTC by mhoshi-vm

# Description

Twitter Exporterを開発版を本番へ移行

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

以下開発の結果

[Twitterお気に入り一覧](https://grafana.dev.cloudnativedays.jp/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:true,%22expr%22:%22social_twitter_favorites%22%7D%5D)

[Retweet一覧](https://grafana.dev.cloudnativedays.jp/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:true,%22expr%22:%22social_twitter_retweets%22%7D%5D)

[感情分析一覧](https://grafana.dev.cloudnativedays.jp/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:true,%22expr%22:%22social_twitter_sentiment%22%7D%5D)

- [ ] I have checked backward/forward compatibility that may cause regarding this change.

2022-02-06 06:58 UTC, sharasoujyu approved these changes
LGTM

2022-02-07 11:25 UTC, iaoiui requested changes

2022-02-07 11:25 UTC, iaoiui commented on manifests/infra/social-analysis/base/deployment.yaml
> +          value: "#o11y2022,#o11y2022_A,#o11y2022_B"
o11y2022の当日のセッションが3並行なので、#o11y2022_Cもあるとよさそうです

2022-02-08 00:19 UTC, mhoshi-vm commented on manifests/infra/social-analysis/base/deployment.yaml
> +          value: "#o11y2022,#o11y2022_A,#o11y2022_B"
ありがとうございます！なおしました。

2022-02-08 01:50 UTC, merged