Import AWS related controllers to Argo in production
cloudnativedaysjp/dreamkast-infra pull request #1437
Opened 2022-02-07 12:45 UTC by inductor

# Description

Fixes https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1213 and https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1243

## Type of change

- [ ] Document update or simple typo fix
- [x] Maintenance/update components
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] I have checked backward/forward compatibility that may cause regarding this change.

2022-02-07 15:04 UTC, ryojsb approved these changes

2022-02-07 15:05 UTC, kntks requested changes

2022-02-07 15:11 UTC, ryojsb requested changes
先ほどApproveをしてしまいましたが、Cluster名に間違いがありましたので、変更します。

2022-02-07 15:57 UTC, kntks commented on manifests/argocd-apps/prd/aws-load-balancer-controller.yaml
> +        value: dreamkast-dev-cluster
```suggestion
        value: dreamkast-cluster
```

2022-02-08 00:03 UTC, kntks approved these changes

2022-02-08 00:13 UTC, ryojsb approved these changes

2022-02-08 02:31 UTC, merged