PrometheusにBasic認証を追加
cloudnativedaysjp/dreamkast-infra pull request #1572
Opened 2022-03-03 14:26 UTC by t4i5uKE

# Description

- 特定のエンドポイントのみアクセスできるように制限
- PrometheusにBasic認証を追加

Fixes # (issue)

## Type of change

- [ ] Document update or simple typo fix
- [ ] Maintenance/update components
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] I have checked backward/forward compatibility that may cause regarding this change.

2022-03-04 15:18 UTC, jacopen requested changes
contour-authserver.yamlという空ファイルも入っちゃってるので削除してくださいー

2022-03-04 15:18 UTC, jacopen commented on manifests/infra/prometheus-ingress/base/auth-server.yaml
> +  secretName: prometheus-htpasswd
auth serverはcontourから叩くものなのと、この機能自体は今後prometheus以外にも使えるものなので、保存フォルダはprometheus-ingressではなくdreamkast-infra/manifests/infra/contour/がいいかなと思います

2022-03-04 15:18 UTC, jacopen commented on manifests/infra/prometheus-ingress/base/cluster-issuer.yaml
> +  selfSigned: {}
これもdreamkast-infra/manifests/infra/contour/かな

2022-03-04 15:18 UTC, jacopen commented on manifests/infra/prometheus-ingress/base/kustomization.yaml
> +- cluster-issuer.yaml
これもフォルダ移行と同時にdreamkast-infra/manifests/infra/contour/側のkustomization.yamlに入れてください

2022-03-04 15:18 UTC, jacopen commented on manifests/infra/prometheus-ingress/overlays/development/certificate.yaml
> +  - prometheus.dev.cloudnativedays.jp
このファイルは不要です！
というのも、 `*.dev.cloudnativedays.jp` というワイルドカードが効いた証明書がcert-manager namespaceにあるので、それを使えばいいからです
```
kubectl get certificate -A
NAMESPACE             NAME                              READY   SECRET                                         AGE
cert-manager          wildcard-dev-cloudnativedays-jp   True    wildcard-dev-cloudnativedays-jp                174d
projectcontour-auth   prometheus                        False   cert-manager/wildcard-dev-cloudnativedays-jp   25h
projectcontour-auth   prometheus-htpasswd               True    prometheus-htpasswd                            25h
projectcontour        prometheus                        False   cert-manager/wildcard-dev-cloudnativedays-jp   26h
```

2022-03-04 15:18 UTC, jacopen commented on manifests/infra/prometheus-ingress/overlays/development/kustomization.yaml
> +- certificate.yaml
この1行は要らなくなるので削除で

2022-03-04 15:18 UTC, jacopen commented on manifests/infra/prometheus-ingress/overlays/production/certificate.yaml
> +    kind: ClusterIssuer
このファイルも不要

2022-03-04 15:18 UTC, jacopen commented on manifests/infra/prometheus-ingress/overlays/development/secret.yaml
> +  auth: dXNlcjE6JGFwcjEkZG9iN0JTWm4kYVFQVnZjYW9MZnlKdFBaUDZMaDlmLwp1c2VyMjokYXByMSRNdHpIWUN3MiRZY3pMYUR2bjQ0T0E1T2hVTFVXUUoxCnVzZXIzOiRhcHIxJEZJMlFsUEVHJGk2QmpWWkNQallqaFIwQTVBakQvNDEK
ExternalSecretsの値送りますね

2022-03-04 15:18 UTC, jacopen commented on manifests/infra/prometheus-ingress/overlays/production/ingress.yaml
> +      secretName: cert-manager/wildcard-dev-cloudnativedays-jp
```suggestion
      secretName: cert-manager/wildcard-cloudnativedays-jp
```

2022-03-04 15:18 UTC, jacopen commented on manifests/infra/prometheus-ingress/overlays/production/ingress.yaml
> +    fqdn: prometheus.dev.cloudnativedays.jp
```suggestion
    fqdn: prometheus.cloudnativedays.jp
```

2022-03-04 15:18 UTC, jacopen commented on manifests/infra/prometheus-ingress/overlays/production/kustomization.yaml
> +- certificate.yaml
この1行は削除で

2022-03-04 15:18 UTC, jacopen commented on manifests/infra/prometheus-ingress/overlays/production/secret.yaml
> +  auth: dXNlcjE6JGFwcjEkZG9iN0JTWm4kYVFQVnZjYW9MZnlKdFBaUDZMaDlmLwp1c2VyMjokYXByMSRNdHpIWUN3MiRZY3pMYUR2bjQ0T0E1T2hVTFVXUUoxCnVzZXIzOiRhcHIxJEZJMlFsUEVHJGk2QmpWWkNQallqaFIwQTVBakQvNDEK
これもExternalSecret送ります

2022-03-04 15:32 UTC, jacopen commented
AWS Secret Managerの
observability/staging-env
observability/production-env

に、prometheus-basic-auth というキーでbasic認証のパスワードを入れておいたので、それをExternal Secretから持ってきて使ってください

2022-03-04 19:00 UTC, t4i5uKE commented on manifests/infra/prometheus-ingress/base/auth-server.yaml
> +  secretName: prometheus-htpasswd
ありがとうございます。確かに仰る通りですね。
移動させます。

2022-03-04 19:00 UTC, t4i5uKE commented on manifests/infra/prometheus-ingress/base/cluster-issuer.yaml
> +  selfSigned: {}
同じく、移動させます。

2022-03-05 09:10 UTC, jacopen approved these changes

2022-03-05 09:10 UTC, merged