Add: Add dashboard "CI/CD2023 Dashboard"
cloudnativedaysjp/dreamkast-infra pull request #2342
Opened 2023-02-21 14:27 UTC by t4i5uKE

# Description

Fixes # (issue)

## Type of change

- [ ] Document update or simple typo fix
- [ ] Maintenance/update components
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] I have checked backward/forward compatibility that may cause regarding this change.

2023-02-21 21:39 UTC, inductor requested changes

2023-02-21 21:39 UTC, inductor commented on dashboards/cicd2023-main.json
> +        "content": "# Dreamkastダッシュボード使い方\n\n主に、CNDT2022で用いている配信プラットフォーム`Dreamkastのメトリクス`を表示するダッシュボードです。\n動画配信のメトリクスに加え、イベントの登録者数などのイベント全体に関わるメトリクスを表示する役割を持ちます。\n\n現在表示しているメトリクスは下記の通りです。\n\n- CNDT202
CNDT2022のままになってる
これ以外もちらほら。

2023-02-23 22:04 UTC, t4i5uKE commented on dashboards/cicd2023-main.json
> +        "content": "# Dreamkastダッシュボード使い方\n\n主に、CNDT2022で用いている配信プラットフォーム`Dreamkastのメトリクス`を表示するダッシュボードです。\n動画配信のメトリクスに加え、イベントの登録者数などのイベント全体に関わるメトリクスを表示する役割を持ちます。\n\n現在表示しているメトリクスは下記の通りです。\n\n- CNDT202
うまく変更ができていなかったので、更新したものに差し替えました

2023-02-24 00:18 UTC, inductor requested changes

2023-02-24 00:18 UTC, inductor commented on dashboards/cicd2023-main.json
> +                "names": ["CNDT2022登録者数"],
これはOK？

2023-02-24 00:18 UTC, inductor commented on manifests/argocd-apps/dev/grafana.yaml
> +          value: "9.0.4"
これはなぜ今ここで変わってる？

2023-02-24 00:18 UTC, inductor commented on dashboards/cicd2023-main.json
> +          "legendFormat": "CI/CD023登録者数",
Typo?

2023-02-24 05:50 UTC, t4i5uKE commented on dashboards/cicd2023-main.json
> +                "names": ["CNDT2022登録者数"],
影響自体は特にないのですが、そもそもこのフィールド自体が不要なので削除しておきます

2023-02-24 05:51 UTC, t4i5uKE commented on dashboards/cicd2023-main.json
> +          "legendFormat": "CI/CD023登録者数",
これは自分のエディタのフォーマットが問題なので修正前に戻します。

2023-02-24 05:54 UTC, t4i5uKE commented on manifests/argocd-apps/dev/grafana.yaml
> +          value: "9.0.4"
自身のフォーマッタの問題なので戻しておきます

2023-02-24 05:56 UTC, t4i5uKE commented on dashboards/cicd2023-main.json
> +          "legendFormat": "CI/CD023登録者数",
Typoなので修正します

2023-02-24 06:18 UTC, inductor commented on manifests/argocd-apps/dev/grafana.yaml
> +            o11y2022-proposals:
このへん全部かえてるのってなんで？

2023-02-24 06:30 UTC, t4i5uKE commented on manifests/argocd-apps/dev/grafana.yaml
> +            o11y2022-proposals:
指定しているファイル名とディレクトリ内に保存されるファイル名が異なっているのが、統一性がなくて微妙だなと思ったからですね。

2023-02-25 14:13 UTC, inductor commented on manifests/argocd-apps/dev/grafana.yaml
> +            o11y2022-proposals:
そういうのはPRのコメントにかいとかないと意図がわからんかもね

2023-02-27 02:26 UTC, t4i5uKE commented on manifests/argocd-apps/dev/grafana.yaml
> +            o11y2022-proposals:
そうですね、確かにそれは後々自分がみてもPRでどのような変更があったのかもわからないですし...

2023-02-27 02:30 UTC, ureuzy approved these changes
LGTM

2023-02-27 04:09 UTC, merged