mail-worker の起動しない不具合の修正
cloudnativedaysjp/dreamkast-infra pull request #747
Opened 2021-09-05 03:12 UTC by oshiro3

## 不具合について

Pod が起動しない不具合を確認.

確認したところ環境変数が設定されておらず、mail-worker の deployment の設定に不足があったことが原因だと思われる.

template に mail-worker の deployment を追加した.

## 確認事項

development 以下で deployment を修正して apply -> ステータスを確認.
https://github.com/cloudnativedaysjp/dreamkast/pull/716 をビルドしてそのイメージで  mail-worker が動作していることを確認.

2021-09-05 03:31 UTC, inductor commented on manifests/app/dreamkast/overlays/template/deployment-mail-worker.yaml
> +    rollingUpdate:
オンボーディングも兼ねてってことだと思ってるので細かい指摘を。これがだめとかってことではないですがマインドの話ですね
ここの値多分デフォルトでついてくる25%の値だと思うんで、「明示的に指定したい」って理由がなければ省いてもどっちでもいいような気はします。好みなんでお任せ。（要は、他のYAMLから流用した値を脳死で使うべからず、くらいな話）

2021-09-05 04:14 UTC, oshiro3 commented on manifests/app/dreamkast/overlays/template/deployment-mail-worker.yaml
> +    rollingUpdate:
ありがとうございます。
ほとんど kubernetes のマニフェスト書いたことがないので助かります。
他のところにもあるし多分必要なんだろうくらいの気持ちで追加してしまったので、以降留意します。
今回のレビューポイントについては、特に明示したい意思はないので削除します。

2021-09-05 07:14 UTC, inductor commented
インフラ的には良いと思うんで @jacopen @takaishi が良さそうならマージしちゃってください

2021-09-05 07:20 UTC, jacopen requested changes
deployment-mail-worker.yamlがkustomizeから参照されていないので、このままだとデプロイされないまま終わっちゃうかな？と。

Review appsに反映させるにはここに追記が必要
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/app/dreamkast/overlays/template/kustomization.yaml

StagingとProductinはReview appsでの動作を確認してから同様にoverlaysへの追加とkustomization.yamlの変更という形でいいかな？

2021-09-05 08:51 UTC, oshiro3 commented
@jacopen 
そんなに環境ごとに変更することはないのかなと思っているので resources のブロックに追加しました。

> StagingとProductinはReview appsでの動作を確認してから同様にoverlaysへの追加とkustomization.yamlの変更という形でいいかな？

一旦 @takaishi さんとその方向で様子を見ようという形で進めています

2021-09-10 08:10 UTC, jacopen approved these changes

2021-09-10 08:10 UTC, merged