Upgrade contour
cloudnativedaysjp/dreamkast-infra pull request #748
Opened 2021-09-05 06:21 UTC by inductor

2021-09-05 07:00 UTC, jacopen commented
baseの変更なので、これを入れてしまうと速攻でProductionにもあたってしまって、問題があった場合の影響が大きいかなと。
なので、まずはbaseではなくoverlayでdevelopment側だけにあてて、動作確認したい

2021-09-05 07:01 UTC, jacopen requested changes
.

2021-09-26 11:43 UTC, inductor commented
@jacopen dev側にうつしました

2021-09-26 15:16 UTC, jacopen commented
overlayにポンおきするだけだとkustomizeが読んでくれないのでこのままだと適用されないまま終わるかとー。

kustomization.yamlの修正も合わせて必要

2021-09-26 15:16 UTC, jacopen requested changes
.

2021-09-27 02:29 UTC, inductor commented on manifests/infra/contour/overlays/development/kustomization.yaml
> -- ../../base
baseと根本的に構造が違ってるのでエラーになっちゃった。別々のYAMLとして管理しないとだめっぽい

2021-10-03 01:18 UTC, merged