Update EKS readme
cloudnativedaysjp/dreamkast-infra pull request #760
Opened 2021-09-10 10:14 UTC by inductor

手順とかいろいろ書いた

2021-09-10 10:17 UTC, inductor commented on cfn/eks-nodes.yaml
> +          - { "Fn::ImportValue": !Sub "${PJPrefix}-eks::ClusterSecurityGroupId" }
共通化できてなかったので

2021-09-10 10:17 UTC, inductor commented on cfn/eks-nodes.yaml
> +    Default: "5"
ここ変数にすればスタック適用し直しの手間が省ける

2021-09-10 10:17 UTC, inductor commented on cfn/eks.yaml
> +    Default: "1.21"
ここもパラメーターにすれば楽

2021-09-11 03:48 UTC, jacopen requested changes

2021-09-11 03:48 UTC, jacopen commented on cfn/rds.yaml
> +    Default: "db"
ここdbにしたのはなぜ？

実際dreamkastが使われてるので、変えると問題起きないかな

https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml#L38-L39

2021-09-11 08:43 UTC, inductor commented on cfn/rds.yaml
> +    Default: "db"
@jacopen fixed

2021-09-12 07:34 UTC, oke-py commented on cfn/eks-nodes.yaml
> +    Default: "5"
昨日ひっかかったやつ
```suggestion
  NodeMaxSize:
    Type: String
    Default: "5"
  NodeMinSize:
    Type: String
    Default: "2"
```

2021-09-12 07:37 UTC, oke-py commented
ここを`dreamkast-dev-cluster`にした。
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/88799f3faf0dc47bb7dadeb5973aeef5e3ecfbf9/cfn/eks.yaml#L44
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/88799f3faf0dc47bb7dadeb5973aeef5e3ecfbf9/cfn/eks-nodes.yaml#L54
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/88799f3faf0dc47bb7dadeb5973aeef5e3ecfbf9/cfn/eks-nodes.yaml#L64
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/88799f3faf0dc47bb7dadeb5973aeef5e3ecfbf9/cfn/eks-nodes.yaml#L73

2021-09-12 12:05 UTC, oke-py approved these changes

2021-09-12 12:06 UTC, merged