add cron job to notify left idea issues
cloudnativedaysjp/dreamkast-infra pull request #853
Opened 2021-09-22 02:09 UTC by takaishi

https://github.com/cloudnativedaysjp/cndt2021/issues/41

2021-09-22 06:38 UTC, takaishi commented
マージされたらクレデンシャルを登録します
Githubのトークンはとりあえず僕のPersonalTokenでいいかな。

2021-09-22 07:17 UTC, jacopen commented
SpreadSheetの件でも思ったけど個人のPersonal access token微妙に嫌だよねぇ。

で、今思い出したんだけど showksユーザーがこのOrgにいるので、こいつのを使えばいいかなと。ちょっとログイン情報探します。
https://github.com/showks-containerdaysjp

2021-09-22 09:54 UTC, jacopen requested changes

2021-09-22 09:54 UTC, jacopen commented on manifests/app/dreamkast/overlays/production/main/cronjob.yaml
> +                      key: SLACK_WEBHOOK_URL
@takaishi https://ap-northeast-1.console.aws.amazon.com/secretsmanager/home?region=ap-northeast-1#!/secret?name=dreamkast-releasebot のGITHUB_TOKENがDk向けのaccess tokenなので、それを使ってくださいな

とはいえreleasebotのsecretを見に行くのは整理的に分かりづらいので、Secrets Managerのdreamkast/production-envにも同じ値を入れて、external secretでとりにいくようにこのファイルを一緒に修正してもらえればと
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/app/dreamkast/overlays/production/main/secret.yaml

2021-09-22 09:54 UTC, jacopen commented on manifests/app/dreamkast/overlays/production/main/cronjob.yaml
> +                      key: SLACK_WEBHOOK_URL
あ、コメント付けるライン間違えたけどTOKENのほうね

2021-09-23 00:10 UTC, takaishi commented on manifests/app/dreamkast/overlays/production/main/cronjob.yaml
> +                      key: SLACK_WEBHOOK_URL
yosage

2021-09-23 01:06 UTC, takaishi commented on manifests/app/dreamkast/overlays/production/main/cronjob.yaml
> +                      key: SLACK_WEBHOOK_URL
SecretsManagerには追加済み。

2021-09-23 01:06 UTC, jacopen approved these changes

2021-09-23 01:06 UTC, merged