StagingとProductionのSQSを作り、Manifestを変更して接続できるようにする
cloudnativedaysjp/dreamkast-infra pull request #902
Opened 2021-09-26 03:08 UTC by oshiro3

メールの非同期送信のためのキューを本番と検証環境でそれぞれのリソースを作成・適用する。

`devMailQueue` -> `dreamkast-prdMailQueue` と `dreamkast-stgMailQueue` に変更しました。
Cloudformation のスタックは作成済みです。

apply していないのでE2Eでの動作確認はできていません。
上記安全に実施する方法があれば教えていただきたいです。

2021-09-26 15:11 UTC, jacopen commented
> メールの非同期送信のためのキューを本番と検証環境でそれぞれのリソースを作成・適用する。
> 
> `devMailQueue` -> `dreamkast-prdMailQueue` と `dreamkast-stgMailQueue` に変更しました。
> Cloudformation のスタックは作成済みです。
> 
> apply していないのでE2Eでの動作確認はできていません。
> 上記安全に実施する方法があれば教えていただきたいです。

これは一旦Stagingのみの修正にして当ててみて、動作確認して問題なければProductionに当てるという形が今のところの妥協点かなと思います

2021-09-27 00:20 UTC, oshiro3 commented
@jacopen 
了解しました
production の変更を削除しました

2021-09-27 00:25 UTC, jacopen requested changes

2021-09-27 00:25 UTC, jacopen commented on manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
> +        - name: SQS_MAIL_QUEUE_URL
こっちのほうにもAWS_REGION入れないとエラー出ちゃうかなと思うのでついかおねしゃす！

2021-09-27 00:29 UTC, oshiro3 commented on manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
> +        - name: SQS_MAIL_QUEUE_URL
追加しました！

2021-09-27 00:29 UTC, jacopen approved these changes

2021-09-27 00:30 UTC, merged